// Code Generated by Sidekick is for learning and experimentation purposes only.
package com.qa.utils;

import java.io.IOException;
import java.io.InputStream;
import java.net.URL;
import java.util.Enumeration;
import java.util.Properties;

public class ConfigReader {

    private Properties prop;

    public Properties init_prop() {
    	prop = new Properties();
        try {
            Enumeration<URL> resources = getClass().getClassLoader().getResources("");
            while (resources.hasMoreElements()) {
                System.out.println("Classpath root: " + resources.nextElement());
            }
            InputStream is = getClass().getClassLoader().getResourceAsStream("config.properties");
            System.out.println("Config file stream: " + is);
            if (is == null) {
                throw new RuntimeException("config.properties not found in classpath!");
            }
            prop.load(is);
        } catch (IOException e) {
            e.printStackTrace();
        }
        return prop;
    }
}


